Use remap instead of republish and remove topic_tools dep
UbiquityRobotics/magni_robot pull request #35
Opened 2017-08-05 23:28 UTC by rohbotics

Fixes #30

@jim-v can you test this, thanks

2017-08-06 06:53 UTC, jim-v requested changes
When I launched `base.launch`, I got this:
```
$ rostopic list | grep cmd_vel
/ubiquity_velocity_controller/cmd_vel
```
After moving the `remap` to inside the `ubiquity_motor` node, it had the correct effect:
```
$ rostopic list | grep cmd_vel
/ubiquity_velocity_controller/cmd_vel
```

2017-08-06 15:59 UTC, rohbotics commented
@jim-v, Updated

2017-08-06 17:27 UTC, jim-v requested changes

2017-08-06 17:27 UTC, jim-v commented on magni_bringup/launch/base.launch
>    <node name="motor_node" pkg="ubiquity_motor" type="motor_node" output="screen"/>
motor_node `<node>` tag should not self-terninate now there is a `</node>`

2017-08-19 16:27 UTC, jim-v approved these changes

2017-08-19 16:32 UTC, merged