Updates for Magni robot simulation in Gazebo.
UbiquityRobotics/magni_robot pull request #70
Opened 2019-02-16 23:06 UTC by Polonium19

Magni robot simulation in Gazebo:
- Gazebo package added.
- URDF description update.

2019-02-17 06:08 UTC, rohbotics commented
Thanks for the PR Petro.

Trying it out I notice a few problems:
- cmd_vel and odom are namespaced under /ubiquity_velocity_controller when they should be global
- The lighting properties for everything but the casters seems to be wrong, as it is all dark
- There are merge conflicts, so you will have to rebase your commits

Let me know if you need any help fixing those.

Looking forward to seeing sonar support.

2019-02-17 18:09 UTC, rohbotics requested changes

2019-02-17 18:09 UTC, rohbotics commented on magni_description/urdf/inertial.xacro
> +Copyright: Osnabrück University, Knowledge Based Systems Group
Add "BSD 3 Clause" to the copyright notice

2019-02-17 18:09 UTC, rohbotics commented on magni_description/urdf/inertial.xacro
> +<robot xmlns:xacro="http://ros.org/wiki/xacro">
This macro has a different scheme url from the other ones. 
```
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://wiki.ros.org/xacro
 new: http://ros.org/wiki/xacro (/home/rohan/melodic_catkin/src/magni_robot/magni_description/urdf/inertial.xacro)
```

2019-02-17 18:09 UTC, rohbotics commented on magni_gazebo/config/magni_controllers.yaml
> +  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
Please use the same covariance as the real robot https://github.com/UbiquityRobotics/magni_robot/blob/indigo-devel/magni_bringup/param/base.yaml#L20

2019-02-18 15:32 UTC, Polonium19 commented
Please check updates for the PR.

2019-02-18 15:40 UTC, rohbotics commented
These changes look good thank you. Please add the sensor support.

2019-02-18 15:41 UTC, rohbotics approved these changes

2019-02-23 04:50 UTC, merged